name: 'Bump Chart Version'
description: Avoids Chart Releaser errors when forgetting to increment the chart version. Works with Chart Releaser {name}-{semver} tags to bump Helm Chart Version if there are chart changes in current branch and release already exists.
author: beehivewarrior
branding:
  icon: anchor
  color: blue

inputs:
  chart_dir:
    description: 'Chart to be bumped'
    required: true
  bump_strategy:
    description: '"patch", "minor", or "major": semver magnitude to bump'
    required: false
    default: patch

outputs:
  version_bumped:
    description: Boolean indicating that the version was incremented.
    value: ${{ steps.bump-chart-version.outputs.version_bumped }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '2'

    - name: Read Helm Chart Before Bump
      id: readChartBefore
      uses: netfoundry/helm-metadata-action@main
      with:
        path: ${{ inputs.chart_dir }}

    - name: Print Helm Chart Version
      run: >
        echo 'INFO: chart name: "${{ steps.readChartBefore.outputs.name }}"'
        echo 'INFO: chart version before bump: "${{ steps.readChartBefore.outputs.version }}"'
      shell: bash

    - name: Fetch latest release version of this chart
      id: latest-release
      uses: netfoundry/latest-release-action@main
      with:
        tag-prefix: ${{ format ('{0}-', steps.readChartBefore.outputs.name) }}

    - name: Check if Chart Changed Since Latest Release
      uses: tj-actions/changed-files@v44
      id: chartChanged
      with:
        files: |
          ${{ inputs.chart_dir }}
        base_sha: ${{ steps.latest-release.outputs.commit-sha }}
    - run: >
        echo 'INFO: check changes result: "${{ steps.chartChanged.outputs.any_modified }}"'
      shell: bash

    - name: Check if a Release Tag Exists
      uses: mukunku/tag-exists-action@v1.2.0
      if: steps.chartChanged.outputs.any_modified == 'true'
      id: checkTag
      with: 
        tag: ${{ format ('{0}-{1}', steps.readChartBefore.outputs.name, steps.readChartBefore.outputs.version) }}
    - name: Print Release Tag Check Result
      run: >
        echo 'INFO: check tag exists result: "${{ steps.checkTag.outputs.exists }}"'
      shell: bash

    - name: Bump the Helm Chart Version
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      uses: netfoundry/helm-chart-pybump-action@main
      with:
        chart-path: ${{ inputs.chart_dir }}
        app_version: false  # only bump chart version, not appVersion
        level: ${{ inputs.bump_strategy }}

    - name: Read Helm Chart After Bump
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      id: readChartAfter
      uses: netfoundry/helm-metadata-action@main
      with:
        path: ${{ inputs.chart_dir }}
    - name: Print Helm Chart Version
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      run: >
        echo 'INFO: chart name: "${{ steps.readChartAfter.outputs.name }}"'
        echo 'INFO: chart version after bump: "${{ steps.readChartAfter.outputs.version }}"'
      shell: bash

    - name: Regenerate Helm Docs if Version Bumped
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      uses: netfoundry/helm-docs-action@main
      with:
        # recursively generate README.md for all charts in comma-sep list of
        # parent dirs
        search-roots: ${{ inputs.chart_dir }}
        git-push: "false"

    - name: Compose Bump Message if Changed
      id: bumpMessage
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      run: |
        echo "bump_message<<OUTER_EOF" >> $GITHUB_OUTPUT
        cat <<'INNER_EOF' >> $GITHUB_OUTPUT
        Bumped "${{ steps.readChartAfter.outputs.name }}" version from "${{ steps.readChartBefore.outputs.version }}" to "${{ steps.readChartAfter.outputs.version }}".
        
        Changes committed by ${{ github.actor }} in commit: ${{ github.event.after }} altered the Helm Chart.
        I updated the "version" in Chart.yaml file using the "${{ inputs.bump_strategy }}" strategy.
        
        Signed-off-by: github-bot[bot] <bot@github.com>
        INNER_EOF
        echo "OUTER_EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Commit Bump if Changed
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      uses: netfoundry/git-push-action@main
      with:
        email: ${{ github.actor }}@github.com
        name: ${{ github.actor }}
        message: |
          ${{ steps.bumpMessage.outputs.bump_message }}
        branch: ${{ github.head_ref || github.ref_name }}
        # use the proposed changes in case of conflict during rebase on the base branch
        strategy: theirs
