name: 'Bump Chart Version'
description: Avoids Chart Releaser errors when forgetting to increment the chart version. Works with Chart Releaser {name}-{semver} tags to bump Helm Chart Version if there are chart changes in current branch and release already exists.
author: beehivewarrior
branding:
  icon: anchor
  color: blue

inputs:
  chart_dir:
    description: 'Chart to be bumped'
    required: true
  bump_strategy:
    description: '"patch", "minor", or "major": semver magnitude to bump'
    required: false
    default: patch

outputs:
  version_bumped:
    description: Boolean indicating that the version was incremented.
    value: ${{ steps.bump-chart-version.outputs.version_bumped }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '2'

    - name: 'Check if Chart Changed'
      uses: tj-actions/changed-files@v35
      id: 'chartChanged'
      with:
        files: |
          ${{ inputs.chart_dir }}
    - run: >
        echo 'INFO: check changes result: "${{ steps.chartChanged.outputs.any_modified }}"'
      shell: bash

    - name: Read Helm Chart
      if: steps.chartChanged.outputs.any_modified == 'true'
      id: readChart
      uses: jacobtomlinson/gha-read-helm-chart@0.1.3
      with:
        path: ${{ inputs.chart_dir }}
    - if: steps.chartChanged.outputs.any_modified == 'true'
      run: >
        echo 'INFO: chart name: "${{ steps.readChart.outputs.name }}"'
        echo 'INFO: chart version: "${{ steps.readChart.outputs.version }}"'
      shell: bash

    - uses: mukunku/tag-exists-action@v1.2.0
      if: steps.chartChanged.outputs.any_modified == 'true'
      id: checkTag
      with: 
        tag: ${{ format ('{0}-{1}', steps.readChart.outputs.name, steps.readChart.outputs.version) }}
    - run: >
        echo 'INFO: check tag exists result: "${{ steps.checkTag.outputs.exists }}"'
      shell: bash

    - name: Bump a Helm Chart Version Locally
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      uses: explorium-ai/bump-helm-chart-action@v2.0.0
      with:
        chart-path: ${{ inputs.chart_dir }}
        app_version: true
        level: ${{ inputs.bump_strategy }}

    - name: "Check For Bump"
      id: review
      if: steps.chartChanged.outputs.any_modified == 'true' && steps.checkTag.outputs.exists == 'true'
      env:
        BUMP_STRATEGY: ${{ inputs.bump_strategy }}
        BUMP_MESSAGE: |
          cat << EOF
          Bumped Helm Chart Version From "$FIRST_MATE_OLD_VERSION" to "$FIRST_MATE_NEW_VERSION"
          
          Changes committed by ${{ github.actor }} in commit: ${{ github.event.after }} altered the Helm Chart.
          I updated the Chart.yaml file using the "BUMP_STRATEGY" strategy.
          
          Signed-off-by: github-bot[bot] <bot@github.com>
          EOF

      run: |
        if [[`git status --porcelain` ]]; then
          git config --local user.name "github-bot"
          git config --local user.email "bot@github.com"
          git add -A
          git commit -m "$BUMP_MESSAGE"
      shell: bash
